/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import Conexion.Conexion;
import Controlador.Controlador_Login;
import Modelo.Modelo_AdministradorDAO;
import Modelo.Modelo_MedicoDAO;
import Modelo.Modelo_PacienteDAO;
import java.sql.*;
import javax.swing.JOptionPane;
import Vistas.Vista_Login;
import Modelo.Modelo_Paciente;

/**
 *
 * @author I'm Max
 */
public class Vista_Paciente extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Paciente
     */
    public Vista_Paciente() {
        
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setIconImage(new ImageIcon(getClass().getResource("../img/sena4.png")).getImage());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        BARRA_PESTAÑAS = new javax.swing.JTabbedPane();
        PANEL_PERFIL = new javax.swing.JPanel();
        PERFIL_PACIENTE = new javax.swing.JPanel();
        PANEL_NORTE_PACIENTE = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LBL_FOTO_PACIENTE = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LBL_VACIO1 = new javax.swing.JLabel();
        LBL_VACIO2 = new javax.swing.JLabel();
        DATOS_PERSONALES_MEDICO1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        lbl_CEDULA_PACIENTE = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl_NOMBRES_PACIENTE = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbl_APELLIDOS_PACIENTE = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_NACIMIENTO_PACIENTE = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl_ESTADO_PACIENTE = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_ENFERMEDAD_PACIENTE = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        PANEL_EAST = new javax.swing.JPanel();
        PANEL_WEST = new javax.swing.JPanel();
        PANEL_CALENDARIO = new javax.swing.JPanel();
        PANEL_NORTE_CALENDARIO = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        PANEL_CENTRAL_CALENDARIO = new javax.swing.JPanel();
        SCROLL_TABLA_CALENDARIO = new javax.swing.JScrollPane();
        TABLA_CALENDARIO = new javax.swing.JTable();
        PANEL_SUR_CALENDARIO = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mn_ARCHIVO = new javax.swing.JMenu();
        MnItem_CerrarSesión = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paciente - Clinisoft");

        BARRA_PESTAÑAS.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        PANEL_PERFIL.setLayout(new java.awt.BorderLayout());

        PERFIL_PACIENTE.setPreferredSize(new java.awt.Dimension(480, 785));
        PERFIL_PACIENTE.setLayout(new java.awt.BorderLayout());

        PANEL_NORTE_PACIENTE.setPreferredSize(new java.awt.Dimension(580, 200));
        PANEL_NORTE_PACIENTE.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        LBL_FOTO_PACIENTE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_FOTO_PACIENTE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/paciente2.png"))); // NOI18N
        jPanel1.add(LBL_FOTO_PACIENTE);

        PANEL_NORTE_PACIENTE.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(4, 1));
        jPanel2.add(LBL_VACIO1);
        jPanel2.add(LBL_VACIO2);

        PANEL_NORTE_PACIENTE.add(jPanel2, java.awt.BorderLayout.EAST);

        PERFIL_PACIENTE.add(PANEL_NORTE_PACIENTE, java.awt.BorderLayout.NORTH);

        DATOS_PERSONALES_MEDICO1.setBackground(new java.awt.Color(255, 255, 255));
        DATOS_PERSONALES_MEDICO1.setLayout(new java.awt.GridLayout(13, 0));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel12.setText("Cédula");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DATOS_PERSONALES_MEDICO1.add(jLabel12);

        lbl_CEDULA_PACIENTE.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lbl_CEDULA_PACIENTE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CEDULA_PACIENTE.setText("CEDULA DEL MEDICO");
        DATOS_PERSONALES_MEDICO1.add(lbl_CEDULA_PACIENTE);

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel14.setText("Nombres");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DATOS_PERSONALES_MEDICO1.add(jLabel14);

        lbl_NOMBRES_PACIENTE.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lbl_NOMBRES_PACIENTE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NOMBRES_PACIENTE.setText("NOMBRE DEL PACIENTE");
        DATOS_PERSONALES_MEDICO1.add(lbl_NOMBRES_PACIENTE);

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel16.setText("Apellidos");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DATOS_PERSONALES_MEDICO1.add(jLabel16);

        lbl_APELLIDOS_PACIENTE.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lbl_APELLIDOS_PACIENTE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_APELLIDOS_PACIENTE.setText("APELLIDO DEL PACIENTE");
        DATOS_PERSONALES_MEDICO1.add(lbl_APELLIDOS_PACIENTE);

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel18.setText("Fecha de Nacimiento");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DATOS_PERSONALES_MEDICO1.add(jLabel18);

        lbl_NACIMIENTO_PACIENTE.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lbl_NACIMIENTO_PACIENTE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NACIMIENTO_PACIENTE.setText("FECHA DE NACIMIENTO DEL PACIENTE");
        DATOS_PERSONALES_MEDICO1.add(lbl_NACIMIENTO_PACIENTE);

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel20.setText("Estado");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DATOS_PERSONALES_MEDICO1.add(jLabel20);

        lbl_ESTADO_PACIENTE.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lbl_ESTADO_PACIENTE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ESTADO_PACIENTE.setText("ESTADO ACTUAL DEL PACIENTE");
        DATOS_PERSONALES_MEDICO1.add(lbl_ESTADO_PACIENTE);

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel23.setText("Enfermedad");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        DATOS_PERSONALES_MEDICO1.add(jLabel23);

        lbl_ENFERMEDAD_PACIENTE.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        lbl_ENFERMEDAD_PACIENTE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ENFERMEDAD_PACIENTE.setText("ENFERMEDAD ACTUAL DEL PACIENTE");
        DATOS_PERSONALES_MEDICO1.add(lbl_ENFERMEDAD_PACIENTE);

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Información Línea Gratuita Nacional 01-8000-950-950");
        DATOS_PERSONALES_MEDICO1.add(jLabel22);

        PERFIL_PACIENTE.add(DATOS_PERSONALES_MEDICO1, java.awt.BorderLayout.CENTER);

        PANEL_PERFIL.add(PERFIL_PACIENTE, java.awt.BorderLayout.CENTER);

        PANEL_EAST.setPreferredSize(new java.awt.Dimension(30, 599));

        javax.swing.GroupLayout PANEL_EASTLayout = new javax.swing.GroupLayout(PANEL_EAST);
        PANEL_EAST.setLayout(PANEL_EASTLayout);
        PANEL_EASTLayout.setHorizontalGroup(
            PANEL_EASTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        PANEL_EASTLayout.setVerticalGroup(
            PANEL_EASTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        PANEL_PERFIL.add(PANEL_EAST, java.awt.BorderLayout.EAST);

        PANEL_WEST.setPreferredSize(new java.awt.Dimension(30, 599));

        javax.swing.GroupLayout PANEL_WESTLayout = new javax.swing.GroupLayout(PANEL_WEST);
        PANEL_WEST.setLayout(PANEL_WESTLayout);
        PANEL_WESTLayout.setHorizontalGroup(
            PANEL_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        PANEL_WESTLayout.setVerticalGroup(
            PANEL_WESTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        PANEL_PERFIL.add(PANEL_WEST, java.awt.BorderLayout.WEST);

        BARRA_PESTAÑAS.addTab("Perfil", PANEL_PERFIL);

        PANEL_CALENDARIO.setLayout(new java.awt.BorderLayout());

        PANEL_NORTE_CALENDARIO.setPreferredSize(new java.awt.Dimension(540, 40));
        PANEL_NORTE_CALENDARIO.setLayout(new java.awt.GridLayout(1, 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        PANEL_NORTE_CALENDARIO.add(jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        PANEL_NORTE_CALENDARIO.add(jPanel5);

        PANEL_CALENDARIO.add(PANEL_NORTE_CALENDARIO, java.awt.BorderLayout.NORTH);

        PANEL_CENTRAL_CALENDARIO.setLayout(new java.awt.BorderLayout());

        TABLA_CALENDARIO = new javax.swing.JTable(){
            public boolean isCellEditable (int row, int colIndex){
                return false;
            }
        };
        TABLA_CALENDARIO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia del Mes", "Hora", "Medicamento"
            }
        ));
        TABLA_CALENDARIO.setFocusable(false);
        SCROLL_TABLA_CALENDARIO.setViewportView(TABLA_CALENDARIO);

        PANEL_CENTRAL_CALENDARIO.add(SCROLL_TABLA_CALENDARIO, java.awt.BorderLayout.CENTER);

        PANEL_CALENDARIO.add(PANEL_CENTRAL_CALENDARIO, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("<html>\n<p align='center' >\nEn esta tabla podrás consultar las fechas y horas para la toma </br> de los medicamentos.\n</p>\n</html>");

        javax.swing.GroupLayout PANEL_SUR_CALENDARIOLayout = new javax.swing.GroupLayout(PANEL_SUR_CALENDARIO);
        PANEL_SUR_CALENDARIO.setLayout(PANEL_SUR_CALENDARIOLayout);
        PANEL_SUR_CALENDARIOLayout.setHorizontalGroup(
            PANEL_SUR_CALENDARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_SUR_CALENDARIOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                .addContainerGap())
        );
        PANEL_SUR_CALENDARIOLayout.setVerticalGroup(
            PANEL_SUR_CALENDARIOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANEL_SUR_CALENDARIOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        PANEL_CALENDARIO.add(PANEL_SUR_CALENDARIO, java.awt.BorderLayout.PAGE_END);

        BARRA_PESTAÑAS.addTab("Calendario", PANEL_CALENDARIO);

        getContentPane().add(BARRA_PESTAÑAS, java.awt.BorderLayout.CENTER);

        Mn_ARCHIVO.setText("Archivo");
        Mn_ARCHIVO.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        MnItem_CerrarSesión.setText("Cerrar Sesión");
        MnItem_CerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItem_CerrarSesiónActionPerformed(evt);
            }
        });
        Mn_ARCHIVO.add(MnItem_CerrarSesión);

        jMenuBar1.add(Mn_ARCHIVO);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnItem_CerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItem_CerrarSesiónActionPerformed
        Vista_Login VistaL = new Vista_Login();
        Modelo_AdministradorDAO ModeloAdmin = new Modelo_AdministradorDAO();
        Modelo_MedicoDAO ModeloMed= new Modelo_MedicoDAO();
        Modelo_PacienteDAO ModeloPac= new Modelo_PacienteDAO();
        Controlador_Login ControladorL = new Controlador_Login(VistaL, ModeloAdmin, ModeloMed, ModeloPac);
        VistaL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MnItem_CerrarSesiónActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane BARRA_PESTAÑAS;
    private javax.swing.JPanel DATOS_PERSONALES_MEDICO1;
    private javax.swing.JLabel LBL_FOTO_PACIENTE;
    private javax.swing.JLabel LBL_VACIO1;
    private javax.swing.JLabel LBL_VACIO2;
    private javax.swing.JMenuItem MnItem_CerrarSesión;
    private javax.swing.JMenu Mn_ARCHIVO;
    private javax.swing.JPanel PANEL_CALENDARIO;
    private javax.swing.JPanel PANEL_CENTRAL_CALENDARIO;
    private javax.swing.JPanel PANEL_EAST;
    private javax.swing.JPanel PANEL_NORTE_CALENDARIO;
    private javax.swing.JPanel PANEL_NORTE_PACIENTE;
    private javax.swing.JPanel PANEL_PERFIL;
    private javax.swing.JPanel PANEL_SUR_CALENDARIO;
    private javax.swing.JPanel PANEL_WEST;
    private javax.swing.JPanel PERFIL_PACIENTE;
    private javax.swing.JScrollPane SCROLL_TABLA_CALENDARIO;
    public javax.swing.JTable TABLA_CALENDARIO;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JLabel lbl_APELLIDOS_PACIENTE;
    public javax.swing.JLabel lbl_CEDULA_PACIENTE;
    public javax.swing.JLabel lbl_ENFERMEDAD_PACIENTE;
    public javax.swing.JLabel lbl_ESTADO_PACIENTE;
    public javax.swing.JLabel lbl_NACIMIENTO_PACIENTE;
    public javax.swing.JLabel lbl_NOMBRES_PACIENTE;
    // End of variables declaration//GEN-END:variables

}
