/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Conexion;
import javax.swing.*;
/**
 *
 * @author I'm Max
 */
public class Prueba_Conexion extends javax.swing.JFrame {

    /**
     * Creates new form Prueba_Conexion
     */
    public Prueba_Conexion() {
        initComponents();
        setSize(400, 100);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brn_conexion1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prueba de Conexión");
        getContentPane().setLayout(new java.awt.GridLayout());

        brn_conexion1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        brn_conexion1.setText("Prueba de Conexión");
        brn_conexion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brn_conexion1ActionPerformed(evt);
            }
        });
        getContentPane().add(brn_conexion1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brn_conexion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brn_conexion1ActionPerformed
        Conexion conect = new Conexion();
        if (conect.getConnection()!=null) {
            JOptionPane.showMessageDialog(null, "Conexión Exitosa");
        }
        else {
            JOptionPane.showMessageDialog(null, "Conexión Fallida");
        }
    }//GEN-LAST:event_brn_conexion1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba_Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba_Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba_Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba_Conexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Prueba_Conexion().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brn_conexion1;
    // End of variables declaration//GEN-END:variables
}
